import api 

name_cuarto1 = api.cuarto_1['name']
objetos = api.cuarto_1['objects']

obj1 = objetos[0]
name_obj1 = obj1['name']
game_obj1 = obj1['game']

name_game_obj1 = game_obj1['name']
premio_game_obj1 = game_obj1['award']
rules_game_obj1 = game_obj1['rules']
questions_game_obj1 = game_obj1['questions']

questions1_game_obj1 = questions_game_obj1[0]
answer1_questions1_game_obj1 = questions1_game_obj1['answer_1']
answer2_questions1_game_obj1 = questions1_game_obj1['answer_2']
answer3_questions1_game_obj1 = questions1_game_obj1['answer_3']
clue1_questions1_game_obj1 = questions1_game_obj1['clue_1']
clue2_questions1_game_obj1 = questions1_game_obj1['clue_2']
clue3_questions1_game_obj1 = questions1_game_obj1['clue_3']

questions2_game_obj1 = questions_game_obj1[1]
answer1_questions2_game_obj1 = questions2_game_obj1['answer_1']
answer2_questions2_game_obj1 = questions2_game_obj1['answer_2']
answer3_questions2_game_obj1 = questions2_game_obj1['answer_3']
clue1_questions2_game_obj1 = questions2_game_obj1['clue_1']
clue2_questions2_game_obj1 = questions2_game_obj1['clue_2']
clue3_questions2_game_obj1 = questions2_game_obj1['clue_3']

questions3_game_obj1 = questions_game_obj1[2]
answer1_questions3_game_obj1 = questions3_game_obj1['answer_1']
answer2_questions3_game_obj1 = questions3_game_obj1['answer_2']
answer3_questions3_game_obj1 = questions3_game_obj1['answer_3']
clue1_questions3_game_obj1 = questions3_game_obj1['clue_1']
clue2_questions3_game_obj1 = questions3_game_obj1['clue_2']
clue3_questions3_game_obj1 = questions3_game_obj1['clue_3']

obj2 = objetos[1]
name_obj2 = obj2['name']
game_obj2 = obj2['game']

name_game_obj2 = game_obj2['name']
requerimiento_obj2 = game_obj2['requirement']
premio_game_obj2 = game_obj2['award']
rules_game_obj2 = game_obj2['rules']
questions_game_obj2 = game_obj2['questions']

questions1_game_obj2 = questions_game_obj2[0]
question_questions1_game_obj2 = questions1_game_obj2['question']
answer_questions1_game_obj2 = questions1_game_obj2['answer']
clue1_questions1_game_obj2 = questions1_game_obj2['clue_1']
clue2_questions1_game_obj2 = questions1_game_obj2['clue_2']
clue3_questions1_game_obj2 = questions1_game_obj2['clue_3']

questions2_game_obj2 = questions_game_obj2[1]
question_questions2_game_obj2 = questions2_game_obj2['question']
answer_questions2_game_obj2 = questions2_game_obj2['answer']
clue1_questions2_game_obj2 = questions2_game_obj2['clue_1']

obj3 = objetos[2]
name_obj3 = obj3['name']
game_obj3 = obj3['game']

name_game_obj3 = game_obj3['name']
requerimiento_obj3 = game_obj3['requirement']
premio_game_obj3 = game_obj3['award']
rules_game_obj3 = game_obj3['rules']
questions_game_obj3 = game_obj3['questions']

questions1_game_obj3 = questions_game_obj3[0]
question_questions1_game_obj3 = questions1_game_obj3['question']
answer_questions1_game_obj3 = questions1_game_obj3['answers']
clue1_questions1_game_obj3 = questions1_game_obj3['clue_1']
clue2_questions1_game_obj3 = questions1_game_obj3['clue_2']
clue3_questions1_game_obj3 = questions1_game_obj3['clue_3']

questions2_game_obj3 = questions_game_obj3[1]
question_questions2_game_obj3 = questions2_game_obj3['question']
answer_questions2_game_obj3 = questions2_game_obj3['answers']
clue1_questions2_game_obj3 = questions2_game_obj3['clue_1']
clue2_questions2_game_obj3 = questions2_game_obj3['clue_2']
clue3_questions2_game_obj3 = questions2_game_obj3['clue_3']

questions3_game_obj3 = questions_game_obj3[2]
question_questions3_game_obj3 = questions3_game_obj3['question']
answer_questions3_game_obj3 = questions3_game_obj3['answers']
clue1_questions3_game_obj3 = questions3_game_obj3['clue_1']
clue2_questions3_game_obj3 = questions3_game_obj3['clue_2']
clue3_questions3_game_obj3 = questions3_game_obj3['clue_3']